### PR TITLE
Add field

### PR DESCRIPTION
**Pull request by bilsch**
@jlambert121 let me know if this branch is cool to merge.

Its doing a few things:

1) the master branch in our fork had a few commits which caused an un-clean merge of upstream. Those reverts should be safe, let me know if they cause funkiness
2) There is a quirk in the systemd service which I fixed ( Set Install section )
3) The service template needed a conditional to handle the location of beaver for venv
4) Added add_field and multiline regexp class params for stanza

### CODE REVIEW

**Comment by everestx** [comment]
I just saw this old PR with failing tests.  I'll try to clean them up while I'm in the kitchen.

**Comment by everestx** [comment]
I fixed the tests above, but the CI build needs to be re-triggered.

**Comment by jlambert121** [comment]
Thanks for fixing up the tests!  Travis is happy now (not sure why it doesn't show it here).  Could you squash all of these down to a single commit and I'll get it merged!

**Comment by jlambert121** [comment]
(or less than 17 anyway)

**Comment by everestx** [comment]
Yep, we can do that.

On Sat, Jan 30, 2016 at 8:09 AM, Justin Lambert <notifications@github.com>
wrote:

> (or less than 17 anyway)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evenup/evenup-beaver/pull/52#issuecomment-177171783>.
>



-- 
Chris Everest

**Pull request closed without merging**
