### PR TITLE
allow version override

### PR DESCRIPTION
**Pull request by bilsch**
Note changed the default value from installed to present

Going forward/backward in versions worked just fine.

Should address https://github.com/evenup/evenup-beaver/issues/40

### CODE REVIEW

**Comment by jlambert121** [comment]
Thanks!  Could you add a test to make sure when a version is passed that it gets set on the package correctly?

**Comment by bilsch** [comment]
@jlambert121 will do thanks!

**Comment by bilsch** [comment]
@jlambert121 thoughts on this - anything else you would like to see here?

**Comment by jlambert121** [comment]
Sorry - GH only notifies on comments, not code changes

**Pull request merged**
